version: '3'
services:
  agent:
    image: "rx-loading:staging"
    stdin_open: true
    tty: true
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
